name: CI/CD with New Relic Monitoring

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up New Relic License Key and Account ID
      - name: Set up environment variables
        run: |
          echo "NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}" >> $GITHUB_ENV
          echo "NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID }}" >> $GITHUB_ENV

      # Run actual tests (replace with your testing command)
      - name: Run tests
        run: |
          echo "Running tests..."
          npm test  # Your actual test command here

      # Send failure data to New Relic if tests fail
      # - name: Send data to New Relic on failure
      #   if: failure()  # This step will only run if previous steps fail
      #   run: |
      #     NEW_RELIC_API_URL="https://api.newrelic.com/v2/applications.json"
      #     curl -X POST $NEW_RELIC_API_URL \
      #       -H "X-Api-Key:${NEW_RELIC_LICENSE_KEY}" \
      #       -H "Content-Type: application/json" \
      #       -d '{
      #           "application": {
      #               "name": "GitHub Actions CI Failure Notification",
      #               "build_status": "failed",
      #               "error_message": "Build failed during tests."
      #           }
      #       }'

      # Output success/failure message
      - name: Output result
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed."
          else
            echo "Tests failed."
          fi
